//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssaultBird2454.VPTU.Installer.UpdaterAPI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UpdaterResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UpdaterResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AssaultBird2454.VPTU.Installer.UpdaterAPI.UpdaterResources", typeof(UpdaterResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://vptu-b790b.firebaseio.com/Software/Update_Info/Latest_Version.json.
        /// </summary>
        internal static string Latest_Version {
            get {
                return ResourceManager.GetString("Latest_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://vptu-b790b.firebaseio.com/Software/Update_Info/Latest_Version_Alpha.json.
        /// </summary>
        internal static string Latest_Version_Alpha {
            get {
                return ResourceManager.GetString("Latest_Version_Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://vptu-b790b.firebaseio.com/Software/Update_Info/Latest_Version_Beta.json.
        /// </summary>
        internal static string Latest_Version_Beta {
            get {
                return ResourceManager.GetString("Latest_Version_Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://vptu-b790b.firebaseio.com/Software/Update_Info/Latest_Version_Master.json.
        /// </summary>
        internal static string Latest_Version_Master {
            get {
                return ResourceManager.GetString("Latest_Version_Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://vptu-b790b.firebaseio.com/Software/Update_Info/Oldest_Version_Allowed.json.
        /// </summary>
        internal static string Oldest_Version_Allowed {
            get {
                return ResourceManager.GetString("Oldest_Version_Allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://vptu-b790b.firebaseio.com/Software/Update_Info.json.
        /// </summary>
        internal static string UpdateInfo_All {
            get {
                return ResourceManager.GetString("UpdateInfo_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://vptu-b790b.firebaseio.com/Software/Update_Info/Versions/[ID].json.
        /// </summary>
        internal static string Version_Get {
            get {
                return ResourceManager.GetString("Version_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://vptu-b790b.firebaseio.com/Software/Update_Info/Version_List.json.
        /// </summary>
        internal static string Version_List {
            get {
                return ResourceManager.GetString("Version_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://vptu-b790b.firebaseio.com/Software/Update_Info/Version_List/Alpha.json.
        /// </summary>
        internal static string Version_List_Alpha {
            get {
                return ResourceManager.GetString("Version_List_Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://vptu-b790b.firebaseio.com/Software/Update_Info/Version_List/Beta.json.
        /// </summary>
        internal static string Version_List_Beta {
            get {
                return ResourceManager.GetString("Version_List_Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://vptu-b790b.firebaseio.com/Software/Update_Info/Version_List/Master.json.
        /// </summary>
        internal static string Version_List_Master {
            get {
                return ResourceManager.GetString("Version_List_Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://vptu-b790b.firebaseio.com/Software/Update_Info/Versions.json.
        /// </summary>
        internal static string Versions {
            get {
                return ResourceManager.GetString("Versions", resourceCulture);
            }
        }
    }
}
